### ISSUE TITLE
Cleanup stale issues and PRs after latest merge

### ISSUE THREAD

**Issue by javiertuya** [giis-uniovi/retorch-st-fullteaching#147]
After latest merge, the system seems to be stable. However, there are several stale issues or PRs in the repo that seem related to flaky behaviours. It is possible that some of them are not necessary now. Check these issues and PRs and eventually close them as wontfix if they are not necessary.

Another thing: PR #143 is one of the three updates related to junit that failed. This PR merges two updates into the third. This is never necessary: if several modules of a repo need to be updated simultaneously, just use the BOM or a property with the version number and dependabot will produce only one update for all modules.

**Comment by augustocristian** [comment]
Hi @javiertuya.
- Yes, I haven't realized now that the version was the same for the 3 libraries.  I've created a property and used to maintain the same version in the 3 libraries.
- Currently, all the branches of Dependabot are ready to being merged into a combined dependency update, are aligned with master and the result must rebase automatically. 
- The PR #125 is ready for being merged into main also  (I've requested your review), I've simplified and removed most of the changes leaving only the essential (the changes into the log conf file) 
- Related to the other PR #132 , I am trying to check if it's necessary, I am pretty sure that yes because the date was not correctly established in the form using the selenium .sendKeys.
- Finally, related to your comment https://github.com/giis-uniovi/retorch-st-fullteaching/pull/145#issuecomment-2298980293 while are the changes would be integrated in main, my idea its cleanup and remove all the comments, TO-DO and refractor the code.
I'll keep you informed about all the progress.
